<?php
/**
{licence}
*/

// 1. Define the constants we need to get going.
define('APPLICATION', 'Vanilla');
define('DS', '/');
// Application Version depends on the Build, which sets it as an environment variable.
define('APPLICATION_VERSION', getenv('VanillaVersion'));

/**
 * File Bootstrap.php, required to initialize Vanilla, is located in the root
 * directory of Vanilla installation, which is three level up from current
 * location.
 */
define('PATH_ROOT', getenv('VanillaRootDir'));

/**
 * IMPORTANT: Read if you're using a Symlink to point to plugin's directory!
 * Comment the previous Define('PATH_ROOT') and uncomment the line below if you're
 * using a Symlink to point to plugin's directory. Command dirname() resolves
 * Symlinks, therefore, the resulting path for PATH_ROOT would be the physical
 * location of the plugin. In such case, simply write the whole absolute path of
 * your Vanilla Installation.
 *
 * Note: there are methods to deal with the issues generated by Symlinks, but, for
 * testing, simply indicating an absolute path is simpler and faster.
 */
//define('PATH_ROOT', 'C:\wamp\www\htdocs\vanilla');

// 2. Include the bootstrap to configure the framework.
echo sprintf("Loading bootstrap file: %s.\n" .
						 "IMPORTANT: if no output is produced, it's probably because the bootstrap " .
						 "file halted the process. One of the most common reasons is that Vanilla was not " .
						 "installed or configured correctly by the build script. In such case, try to open " .
						 "the forum home page. If it asks for configuration parameters, then the setup was " .
						 "not completed correctly.\n",
						 PATH_ROOT . '/bootstrap.php');
require_once(PATH_ROOT . '/bootstrap.php');
echo 'Bootstrap completed.';
